[package]
name = "logria"
version = "0.1.0"
authors = ["Christopher Sardegna <logria@reagentx.net>"]
edition = "2018"
repository = "https://github.com/ReagentX/Logria"
readme = "README.md"
description = "A powerful CLI tool that puts log analytics at your fingertips."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "3.0.0-beta.4"
dirs = "4.0.0"
crossterm = "0.21.0"
regex = "1.5.4"
tokio = { version = "1.12.0", features = [
    "process",
    "io-util",
    "rt-multi-thread",
    "macros",
] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.59"
time = { version = "0.3.2", features = ["formatting", "parsing"] }
