[package]
name = "logria"
version = "0.1.0"
authors = ["Christopher Sardegna <logria@reagentx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
dirs = "3.0.1"
crossterm = "0.18.2"
regex = "1"
tokio = {version = "0.3.5", features = ["process", "io-util", "rt-multi-thread", "macros"]}
