[package]
name = "logria"
version = "0.0.0"
authors = ["Christopher Sardegna <logria@reagentx.net>"]
edition = "2021"
repository = "https://github.com/ReagentX/Logria"
readme = "README.md"
description = "A powerful CLI tool that puts log analytics at your fingertips."
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "2.34.0"
dirs = "4.0.0"
crossterm = "0.22.1"
regex = "1.5.4"
tokio = { version = "1.15.0", features = [
    "process",
    "io-util",
    "rt-multi-thread",
    "macros",
] }
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0.59"
time = { version = "0.3.5", features = ["formatting", "parsing"] }
format_num = "0.1.0"
