name: Release

on:
  release:
    types: [created]


env:
  CARGO_TERM_COLOR: always

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: |
          sed -i "s/0\.0\.0/${{ github\.event\.release\.tag_name }}" Cargo.toml
          cargo publish --dry-run
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
