name: Test

on:
  pull_request:
    branches:
        - release
        - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Rust
      uses: actions/checkout@v4
      run: |
        rustup update stable && rustup default stable
    - name: Run tests
      uses: actions/checkout@v4
      run: cargo test --verbose
    - name: Run linting
      run: cargo clippy
