name: Test

on:
  pull_request:
    branches:
        - release
        - develop

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
